export { default as Test } from './Test';
export { default as Landing } from './Landing';
export { default as Login } from './Login';
export { default as LoginType } from './LoginType';
export { default as Register } from './Register';
export { default as RegisterType } from './RegisterType';
export { default as Home } from './Home';
export { default as Output } from './Output';
export { default as MyProfile } from './MyProfile';
export { default as EditProfile } from './EditProfile';
export { default as ChangePassword } from './ChangePassword';
export { default as AdminHome } from './AdminHome';
export { default as AdminNewEntry } from './AdminNewEntry';
// export { default as EditProfile } from './EditProfile';
// export { default as Containers } from './Containers';
